//
// Created by ben on 18/10/16.
//

#ifndef PROJECT_SYSCALL_AS_H_H
#define PROJECT_SYSCALL_AS_H_H

#define SYSCALL_NO_LINUX 313
#define SYSCALL_BUFFERVM 2
#define SYSCALL_MAX SYSCALL_NO_LINUX + SYSCALL_BUFFERVM

#endif //PROJECT_SYSCALL_AS_H_H
